AllCops:
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*.rb'
Style/Documentation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/UriEscapeUnescap:
  Enabled: false
